#!/usr/bin/env bash

# Make vim the default editor.
export EDITOR='vim';

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8';

# Increase Bash history size. Allow 32³ entries; the default is 500.
export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}";
# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth';

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';
if [[ `uname` == 'Darwin' ]]; then
	export PATH="$(brew --prefix)/opt/coreutils/libexec/gnubin:$PATH"
fi

export PATH="$HOME/bin:$HOME/.local/bin:$PATH"
export PIPENV_VENV_IN_PROJECT=1

export XTERM=xterm-256color
