set -g default-terminal "xterm-256color"

set -g mouse on

bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

bind-key M split-window -h "vim ~/.tmux.conf"

bind-key G split-window -h "cd ~/.dotfiles; git commit -a -m 'Update'; git push"
