set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"

set -g mouse on

bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

bind-key M split-window -h "vim ~/.tmux.conf"

bind-key G split-window -h "cd ~/.dotfiles; git commit -a -m 'Update'; git push"

bind '"' split-window -c "\#{pane_current_path}"

bind % split-window -h -c "\#{pane_current_path}"

bind-key c new-window -c "\#{pane_current_path}"
