#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# make sure requirements.txt is up to date with every commit
# by comparing the output of pip freeze

if [ -r pyproject.toml ]; then

	echo "Running poetry -> requirements.txt"
	poetry export -f requirements.txt -o requirements_new.txt --without-hashes
	if [ -r requirements.txt ]; then
		diff requirements.txt requirements_new.txt > /dev/null
		if [$? != 0 ]; then
			mv requirements_new.txt requirements.txt
			git add requirements.txt
		else
			rm requirements_new.txt
		fi
	else
		mv requirements_new.txt requirements.txt
		git add requirements.txt
	fi

elif [ -r requirements.txt ]; then
	pip freeze | diff requirements.txt - > /dev/null
	if [ $? != 0 ]; then
	    echo "Missing python module dependencies in requirements.txt. Run 'pip freeze > requirements.txt' to update."
	    exit 1
	else
		echo "requirements.txt upto date"
	fi
fi

