#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# make sure requirements.txt is up to date with every commit
# by comparing the output of pip freeze

if [ -r requirements.txt ]; then
	pip freeze | diff requirements.txt - > /dev/null
	if [ $? != 0 ]; then
	    echo "Missing python module dependencies in requirements.txt. Run 'pip freeze > requirements.txt' to update."
	    exit 1
	else
		echo "requirements.txt upto date"
	fi
fi



